name: Galaxy FOTA Ultimate Auto
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install httpx
      - run: python checker.py
      - name: Save Results
        run: |
          git config --global user.name 'Galaxy-Bot'
          git config --global user.email 'bot@galaxy.com'
          git add data.json
          git commit -m "Capture: Latest Firmware [skip ci]" || exit 0
          git push origin main --force
